<?php
if(!defined('ROOT_PATH')) exit;
$config = content_config($type); $model = $config['model'];
if (($_SERVER['REQUEST_METHOD'] ?? 'GET') === 'POST') {
    verify_csrf();
    if (input('_action') !== 'delete') { http_response_code(400); exit('Invalid action.'); }
    $item = $model::find((int)input('id'));
    if (!$item) not_found();
    $model::delete((int)$item['id']); if($config['image']) delete_upload($item['image']);
    flash('success',$config['singular'] . ' deleted.'); redirect(url('admin/'.$type.'/index.php'));
}
$search = substr(query('q'),0,100); $result = $model::paginate(max(1,(int)query('page','1')),10,$search);
admin_header($config['label'],$type,'Create, edit and publish your ' . strtolower($config['label']) . '.');
?><div class="flex flex-col sm:flex-row justify-between gap-4 mb-6"><form class="flex gap-2 max-w-lg" method="get" role="search"><label for="q" class="sr-only">Search <?= e($config['label']) ?></label><input id="q" type="search" name="q" maxlength="100" value="<?= e($search) ?>" placeholder="Search by title…"><button class="btn btn-neutral" type="submit" aria-label="Search"><?= icon('search') ?></button></form><a class="btn btn-primary" href="<?= e(url('admin/'.$type.'/create.php')) ?>"><?= icon('plus','w-4 h-4') ?>Add <?= e(strtolower($config['singular'])) ?></a></div><section class="card overflow-hidden"><div class="overflow-x-auto"><table class="admin-table"><thead><tr><th>Title</th><th>Status</th><th>Updated</th><th class="text-right">Actions</th></tr></thead><tbody><?php foreach($result['items'] as $row): ?><tr><td class="min-w-[240px]"><a href="<?= e(url('admin/'.$type.'/edit.php?id='.$row['id'])) ?>" class="font-semibold hover:text-brand-600"><?= e($row['title']) ?></a><p class="text-xs text-muted mt-1"><?= e($row['slug']) ?></p></td><td><?= badge($row['status']) ?></td><td class="whitespace-nowrap"><?= e(date('M j, Y',strtotime($row['updated_at']))) ?></td><td><div class="flex items-center justify-end gap-2"><?php if($row['status']==='published'): ?><a class="btn btn-neutral btn-small" aria-label="View <?= e($row['title']) ?>" href="<?= e(page_url($config['page'],['slug'=>$row['slug']])) ?>" target="_blank" rel="noopener"><?= icon('eye','w-4 h-4') ?></a><?php endif ?><a class="btn btn-neutral btn-small" aria-label="Edit <?= e($row['title']) ?>" href="<?= e(url('admin/'.$type.'/edit.php?id='.$row['id'])) ?>"><?= icon('edit','w-4 h-4') ?></a><form method="post" data-confirm="Delete this <?= e(strtolower($config['singular'])) ?> permanently? This cannot be undone."><?= csrf_field() ?><input type="hidden" name="id" value="<?= (int)$row['id'] ?>"><input type="hidden" name="_action" value="delete"><button class="btn btn-neutral btn-small text-red-600" type="submit" aria-label="Delete <?= e($row['title']) ?>"><?= icon('trash','w-4 h-4') ?></button></form></div></td></tr><?php endforeach ?><?php if(!$result['items']): ?><tr><td colspan="4" class="text-center py-12"><p class="text-muted">No <?= e(strtolower($config['label'])) ?> found.</p></td></tr><?php endif ?></tbody></table></div></section><p class="text-sm text-muted mt-4"><?= $result['total'] ?> item<?= $result['total']===1?'':'s' ?></p><?php view('layouts/pagination',['page'=>$result['page'],'pages'=>$result['pages'],'paginationUrl'=>url('admin/'.$type.'/index.php'),'paginationParams'=>['q'=>$search]]); admin_footer(); ?>
