<?php
if(!defined('ROOT_PATH')) exit;
$config = (require ROOT_PATH . '/app/config/admin_content.php')[$section]; $model = $config['model'];
if (($_SERVER['REQUEST_METHOD'] ?? 'GET') === 'POST') {
    verify_csrf();
    if(input('action') !== 'delete') { http_response_code(400); exit('Invalid action'); }
    $item = $model::find((int)input('id')); if(!$item) not_found();
    $model::delete((int)$item['id']); if($config['image']) delete_upload($item['image']);
    flash('success',ucfirst($config['singular']).' deleted.'); redirect(url('admin/'.$section.'/index.php'));
}
$search = substr(query('q'),0,100); $result = $model::paginate(max(1,(int)query('page','1')),10,$search);
admin_start($config['title'],$section,'Create, edit and publish your '.$config['title'].'.');
?>
<div class="flex flex-col sm:flex-row justify-between gap-4 mb-6"><form method="get" class="flex gap-2 max-w-md"><label class="sr-only" for="search">Search <?= e($config['title']) ?></label><input id="search" type="search" name="q" value="<?= e($search) ?>" maxlength="100" placeholder="Search by title…"><button class="btn btn-neutral" type="submit" aria-label="Search"><?= icon('search') ?></button></form><a class="btn btn-primary self-start" href="<?= e(url('admin/'.$section.'/create.php')) ?>"><?= icon('plus','w-4 h-4') ?>New <?= e($config['singular']) ?></a></div>
<section class="card overflow-hidden"><div class="overflow-x-auto"><table class="admin-table"><thead><tr><th scope="col">Title</th><th scope="col">Status</th><th scope="col">Updated</th><th scope="col" class="text-right">Actions</th></tr></thead><tbody><?php foreach($result['items'] as $item): ?><tr><td><a href="<?= e(url('admin/'.$section.'/edit.php?id='.$item['id'])) ?>" class="font-semibold hover:text-brand-600"><?= e($item['title']) ?></a><p class="text-xs text-muted mt-1"><?= e($item['slug']) ?></p></td><td><?= badge($item['status']) ?></td><td class="whitespace-nowrap"><?= e(date('M j, Y',strtotime($item['updated_at']))) ?></td><td><div class="flex items-center justify-end gap-3"><?php if($item['status']==='published'): ?><a class="p-2 text-muted hover:text-brand-600" href="<?= e(page_url($config['page'],['slug'=>$item['slug']])) ?>" target="_blank" rel="noopener" aria-label="View <?= e($item['title']) ?>"><?= icon('eye','w-4 h-4') ?></a><?php endif ?><a class="p-2 text-brand-700" href="<?= e(url('admin/'.$section.'/edit.php?id='.$item['id'])) ?>" aria-label="Edit <?= e($item['title']) ?>"><?= icon('edit','w-4 h-4') ?></a><form method="post" data-confirm="Delete this <?= e($config['singular']) ?>? This cannot be undone."><?= csrf_field() ?><input type="hidden" name="action" value="delete"><input type="hidden" name="id" value="<?= $item['id'] ?>"><button type="submit" class="p-2 text-red-600" aria-label="Delete <?= e($item['title']) ?>"><?= icon('trash','w-4 h-4') ?></button></form></div></td></tr><?php endforeach ?><?php if(!$result['items']): ?><tr><td colspan="4" class="text-center py-10 text-muted">No <?= e(strtolower($config['title'])) ?> found. Try another search or add your first one.</td></tr><?php endif ?></tbody></table></div></section><p class="text-sm text-muted mt-4"><?= $result['total'] ?> <?= e(strtolower($config['title'])) ?> total</p>
<?php view('layouts/pagination',['page'=>$result['page'],'pages'=>$result['pages'],'paginationUrl'=>url('admin/'.$section.'/index.php'),'paginationParams'=>['q'=>$search]]); admin_end(); ?>
