<section class="page-intro"><div class="container-page"><p class="eyebrow">Let’s start a conversation</p><h1>Your next big idea<br><span class="text-brand-500">starts here.</span></h1><p class="mt-6 text-lg text-muted max-w-xl">Have a project in mind? Tell us a little about it and we’ll take it from there.</p></div></section><section class="container-page section-space grid lg:grid-cols-[.8fr_1.2fr] gap-12 lg:gap-20"><div><h2 class="section-title">Say hello.</h2><p class="text-muted mt-4 mb-8">A quick question or a fresh brief — we’d love to hear what you’re thinking.</p><div class="space-y-7"><?php foreach([['mail','Email us',setting('contact_email','hello@example.com')],['phone','Give us a call',setting('contact_phone','Add your phone number in settings')],['pin','Find us',setting('contact_address','Dhaka, Bangladesh')]] as $item): ?><?php if(trim($item[2])==='') continue; ?><div class="flex gap-4"><span class="w-12 h-12 flex-none rounded-xl bg-brand-50 text-brand-600 flex items-center justify-center"><?= icon($item[0]) ?></span><div><h3 class="font-semibold text-base"><?= e($item[1]) ?></h3><p class="text-muted mt-1 break-words"><?php if($item[0]==='mail'): ?><a href="mailto:<?= e($item[2]) ?>"><?= e($item[2]) ?></a><?php elseif($item[0]==='phone' && preg_match('/[0-9]{5,}/',preg_replace('/\D/','',$item[2]))): ?><a href="tel:<?= e(preg_replace('/[^+0-9]/','',$item[2])) ?>"><?= e($item[2]) ?></a><?php else: ?><?= e($item[2]) ?><?php endif ?></p></div></div><?php endforeach ?></div><div class="mt-10 p-6 rounded-2xl bg-brand-50"><p class="font-semibold text-sm">Office hours</p><p class="text-muted text-sm mt-2"><?= e(setting('office_hours','Sunday–Thursday · 10am–6pm')) ?></p></div></div>
<div class="card p-6 md:p-9" id="contact-form"><h2 class="text-2xl font-bold mb-6">Tell us about your project</h2><?php foreach(flashes() as $message): ?><div role="status" class="flash flash-<?= e($message['type']) ?>"><?= e($message['message']) ?></div><?php endforeach ?><?php if($errors): ?><div class="flash flash-error" role="alert"><p class="font-semibold">Please check the fields below.</p><ul class="list-disc pl-5 mt-2"><?php foreach($errors as $error): ?><li><?= e($error) ?></li><?php endforeach ?></ul></div><?php endif ?>
<form method="post" action="<?= e(page_url('contact')) ?>#contact-form">
  <?= csrf_field() ?>
  <div class="grid sm:grid-cols-2 gap-5"><div><label for="name">Your name <span class="text-brand-600">*</span></label><input id="name" name="name" autocomplete="name" required maxlength="100" value="<?= e($old['name'] ?? '') ?>"></div><div><label for="email">Email address <span class="text-brand-600">*</span></label><input type="email" id="email" name="email" autocomplete="email" required maxlength="190" value="<?= e($old['email'] ?? '') ?>"></div><div><label for="phone">Phone <span class="text-muted font-normal">(optional)</span></label><input type="tel" id="phone" name="phone" autocomplete="tel" maxlength="40" value="<?= e($old['phone'] ?? '') ?>"></div><div><label for="service">I'm interested in</label><select id="service" name="service"><option value="">Let's figure it out</option><?php foreach($services as $service): ?><option value="<?= e($service['title']) ?>" <?= ($old['service'] ?? '') === $service['title'] ? 'selected' : '' ?>><?= e($service['title']) ?></option><?php endforeach ?></select></div></div>
  <div class="mt-5"><label for="budget">Project budget <span class="text-muted font-normal">(optional)</span></label><select id="budget" name="budget"><?php foreach([''=>'Select a range','Under ৳25,000'=>'Under ৳25,000','৳25,000–৳75,000'=>'৳25,000–৳75,000','৳75,000–৳200,000'=>'৳75,000–৳200,000','৳200,000+'=>'৳200,000+','Let’s discuss'=>'Let’s discuss'] as $value=>$label): ?><option value="<?= e($value) ?>" <?= ($old['budget'] ?? '')===$value?'selected':'' ?>><?= e($label) ?></option><?php endforeach ?></select></div>
  <div class="mt-5"><label for="message">What do you have in mind? <span class="text-brand-600">*</span></label><textarea id="message" name="message" required maxlength="5000" rows="5" placeholder="A little about your business, your goals and your timeline…"><?= e($old['message'] ?? '') ?></textarea></div>
  <label class="flex items-start gap-3 text-sm text-muted font-normal mt-5"><input type="checkbox" name="consent" value="1" checked class="flex-none mt-1">I agree that BrandBuzz may use these details to respond to my enquiry.</label>
  <button class="btn btn-primary w-full mt-5" type="submit">Send your message <?= icon('arrow','w-4 h-4') ?></button><p class="text-xs text-muted mt-4">Your details will be used to respond to this enquiry.</p>
</form></div></section>
