<?php
require __DIR__ . '/_init.php';
admin_start('A little overview.','dashboard','Your content, projects and conversations in one place.');
$recent = array_slice(Contact::all(),0,5);
?>
<div class="grid sm:grid-cols-2 xl:grid-cols-4 gap-5 mb-8"><?php foreach([['Services',Service::count(),'megaphone','services/index.php'],['Projects',Project::count(),'folder','projects/index.php'],['Blog posts',Blog::count(),'file','blogs/index.php'],['New messages',Contact::unread(),'mail','contacts/index.php?status=new']] as $stat): ?><a class="stat-card hover:shadow-lift transition" href="<?= e(url('admin/'.$stat[3])) ?>"><div class="flex justify-between items-center"><p class="text-muted text-sm"><?= e($stat[0]) ?></p><span class="text-brand-600 bg-brand-50 rounded-xl p-3"><?= icon($stat[2]) ?></span></div><p class="text-4xl font-bold mt-3"><?= $stat[1] ?></p></a><?php endforeach ?></div>
<div class="grid xl:grid-cols-[1.6fr_1fr] gap-6"><section class="card overflow-hidden"><div class="p-6 flex justify-between gap-4 items-center"><h2 class="font-bold text-xl">Latest conversations</h2><a class="link-arrow" href="<?= e(url('admin/contacts/index.php')) ?>">View all</a></div><?php if($recent): ?><div class="overflow-x-auto"><table class="admin-table"><thead><tr><th scope="col">From</th><th scope="col">Service</th><th scope="col">Status</th><th scope="col">Open</th></tr></thead><tbody><?php foreach($recent as $item): ?><tr><td><p class="font-semibold"><?= e($item['name']) ?></p><p class="text-xs text-muted mt-1"><?= e($item['email']) ?></p></td><td><?= e($item['service'] ?: 'General enquiry') ?></td><td><?= badge($item['status']) ?></td><td><a class="link-arrow" href="<?= e(url('admin/contacts/view.php?id='.$item['id'])) ?>">Read</a></td></tr><?php endforeach ?></tbody></table></div><?php else: ?><div class="p-10 pt-3"><p class="text-muted">No messages yet. New enquiries from your contact page will appear here.</p><a class="btn btn-outline mt-6" href="<?= e(page_url('contact')) ?>">Open contact page</a></div><?php endif ?></section><section class="card p-7"><p class="eyebrow">Keep things fresh</p><h2 class="text-2xl font-bold">What would you like<br>to create today?</h2><div class="flex flex-col gap-3 mt-7"><a class="btn btn-primary" href="<?= e(url('admin/projects/create.php')) ?>"><?= icon('plus','w-4 h-4') ?>Add a project</a><a class="btn btn-neutral" href="<?= e(url('admin/blogs/create.php')) ?>">Write a blog post</a><a class="btn btn-neutral" href="<?= e(url('admin/hero/manage.php')) ?>">Update homepage</a></div></section></div>
<div class="mt-7 p-5 bg-brand-50 rounded-xl text-sm text-brand-700">The supplied projects and testimonials are demo content. Update your contact details and replace the examples before launching.</div>
<?php admin_end(); ?>
